#数据库连接配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ticket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #关闭模板引擎缓存
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379

#配置端口号
server:
  port: 8080


